[project]
name = "vercel-flask-starter"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "flask>=3.1,<4.0",
  "gunicorn~=23.0.0",
  "numpy>=1.21",
  "pandas>=1.4",
  "scikit-learn>=1.2",
  "flask-cors>=4.0",
  "paho-mqtt>=1.6"
]
